### ISSUE TITLE
[Feature request] Show the transaction priority of transactions in the pool

### ISSUE THREAD

**Issue by leafcutterant** [moneroexamples/onion-monero-blockchain-explorer#107]
"Fee" is a nice metric to have, but it would be also very helpful to know what priority multiplier is used by a transaction in the pool.

**Comment by moneroexamples** [comment]
I will think about this. The problem is that it might be difficult to get priority level from the fee, as priority is a thing in offical monero wallets. Web wallets, mobile wallets, custom modified monero wallets may not use (or have different) definition of priority levels. But maybe some rough estimate would be possible.

**Comment by leafcutterant** [comment]
I see. Any other quantification would be nice, too, like XMR/kb.

An estimation to priority level would be useful so those using the core wallet can gauge their fees.

(I had the impression that the protocol enforces the fixed fee priorities, but this is obviously not the case.)

**Comment by moneroexamples** [comment]
I added per_kB fee to transaction  pool list and tx details view. At the moment development version of the explorer is not being hosted, but this is how it looks like on a screenshot https://i.imgur.com/psduXvo.png

Priority level wont be added probably, because it depends on dynamic fee_per_kb which changes in monero network. So to have the priority calculated for any past txs, the explorer would need to keep track of all the historical dynamic fees.

**Comment by leafcutterant** [comment]
Thank you for implementing it! Closing it then.
