### ISSUE TITLE
View Key JSON API

### ISSUE THREAD

**Issue by dternyak** [moneroexamples/onion-monero-blockchain-explorer#131]
Inspired by https://twitter.com/btcven/status/1008935633778348032

> Does @MoneroVision have an API where the view key could be passed/used to be able to check if a payment has arrived to a Monero address?

For MoneroVision.com, it would be useful for us if onion-monero-blockchain-explorer had a JSON API where passing a viewkey could return all outputs associated with the viewkey.

@moneroexamples I think open-monero has similar functionality, so perhaps implementation could be as simple as porting the logic over.

Happy to help develop the JSON API spec if requested!

**Comment by moneroexamples** [comment]
Using json api on the onion explorer you can only check for your outputs in a single tx: https://github.com/moneroexamples/onion-monero-blockchain-explorer#apioutputstxhashtx_hashaddressviewkeytxprove01

or last few blocks:

https://github.com/moneroexamples/onion-monero-blockchain-explorer#apioutputsblocks

Obviously  the last call could easily be modified to use , e.g. last 1000 blocks, instead of 5 what it does now. However, scanning the entire blockchain for your outputs is a very resource heavy operation, thus I don't think its good idea to put it in the explorer. Maybe last 100, 1000 blocks would be fine, depending on your computer and number of users. 

Something like this would be best as a separate service in my view. And such online service has already been developed before (https://github.com/moneroexamples/onion-monero-viewer) and was live online, but it got discontinued. Since then I have had not time to revisit this idea unfortunately.

**Comment by t-900-a** [comment]
This should be closed.
It is addressed via openmonero: https://github.com/moneroexamples/openmonero
