### ISSUE TITLE
can't compile with either master or release-v0.13

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-blockchain-explorer#164]
its me again, can't compile.

**Comment by moneroexamples** [comment]
Any error? And what linux? ubuntu 16.04?
And which branch of the explorer? master or devel?

**Comment by Gingeropolous** [comment]
both master and devel of onion. both master and release for monero. 

Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-137-generic x86_64)

http://paste.debian.net/1068128/

**Comment by moneroexamples** [comment]
Looking into it now. Just a quick question. You are building monero with `USE_SINGLE_BUILDDIR=1 make`? If you forgot the flag, the new build folder wont be detected by the explorer, and it will be using the old one (i.e. one build previously with that flag).

**Comment by Gingeropolous** [comment]
i just tried it with that and got the same error..

http://paste.debian.net/1068194/

**Comment by moneroexamples** [comment]
I think the issue is a mismatch between monero and the explorer versions.  The error you see regarding `get_output_key` is due to changes in api for the function in recent monero version. It should have been fixed in the explorer a while back, so just to be on the same page. 

You just compiled current (like in today's version) of monero from its `master` branch using `USE_SINGLE_BUILDDIR=1 make`? 

And then you use current explorer version from its `devel` branch? If you use `master` branch of the explorer, this could explain the issue.

**Comment by Gingeropolous** [comment]
ok, i tried all of that. somehow, it seems my testnet was on some different database version that I can't figure out. I nuked the data. mdb and am resyncing with release-v013. Once thats finished i'll see if the explorer works. Got the explorer to compile though.

**Comment by moneroexamples** [comment]
That's good to hear it compiles now. 

Let me know how it goes with testnet. I assume mainnet and stagenet are working?

**Comment by Gingeropolous** [comment]
Hah! I figur3ed it out.

OK, so the new fork is using the release-v013 branch.

You need to use master of onion-explorer .

**Comment by moneroexamples** [comment]
Thanks. I will updated readme on master branch of the onion-explorer.
