### ISSUE TITLE
MDB_READERS_FULL: Environment maxreaders limit reached

### ISSUE THREAD

**Issue by normoes** [moneroexamples/onion-monero-blockchain-explorer#169]
After compiling the monero-onion-explorer with monero (on branch `v0.14.0.2`) I get the error below, when running **xmrblocks** - Regardless of the monero-onion-explorer branch (`devel` or `master`):

```
2019-03-13 18:34:46.022    7f83cb4ff7c0    WARN blockchain.db.lmdb    src/blockchain_db/lmdb/db_lmdb.cpp:76    Failed to create a read transaction for the db: MDB_READERS_FULL: Environment maxreaders limit reached
terminate called after throwing an instance of 'cryptonote::DB_ERROR_TXN_START'
what(): Failed to create a read transaction for the db: MDB_READERS_FULL: Environment maxreaders limit reached
```

The explorer is the only thing working with that daemon, by the way.

It doesn't even start, it happens right at the beginning.

How can I compile the explorer correclty to use it with monerod `v0.14.0.2`?

Thanks.

**Comment by moneroexamples** [comment]
I know what is this error, I was dealing with it in other projects, e.g., https://github.com/moneroexamples/openmonero/issues/127

The thing is that it should not have occurred for the explorer, due to how the explorer works. But anyway, can try to reduce number of threads in the monero itself as shown here: https://github.com/monero-project/monero/issues/2741#issuecomment-340524350

Also can remove `lock.mdb` so that new, fresh one is created when you start the daemon. Example location of the file is `~/.bitmonero/lmdb/lock.mdb`.

**Comment by normoes** [comment]
OK, I avoided synchronizing the blockchain again and added `--max-concurrency 60` as a `monerod` option.

This did the trick.

Thanks @moneroexamples

**Comment by moneroexamples** [comment]
No problem. Its good that it worked.

> By the way, I now use monero (on branch v0.14.0.2) and the monero-onion-explorer (on branch master).

That is fine. For now I wait till all changes from monero branch v0.14.0.2 (called `release-v0.13`; confusing name, I know) get merged to `master` of monero. Or maybe new branch will be created on monero for `0.14.1`? At the moment there is some confusion about the naming of different branches in monero. This causes uncertainty which branch should be used for moneroexamples projects as well. Hopefully branch names will get sorted out before monero v0.14.1 arrives.

**Comment by hyc** [comment]
You don't need to delete the lock file. You merely need to stop all processes that are using it, and it will automatically be reset the next time any process opens the environment.

The default number of readers is 126. If you're going to have many processes using the same database simultaneously, such that the total count of threads accessing the DB is greater than 126, then you should make sure that the first process to open the DB calls mdb_env_set_maxreaders() with a large enough number.

Also make sure your processes are exiting cleanly, and aren't just dying on a signal or something, so that the reader cleanup will occur when a thread exits. Otherwise you'll accumulate a lot of stale readers, and they will hang around as long as any process has the environment open. You can add a stale reader check call periodically inside your code to clean these up, or use the mdb_stat program externally to do the same thing.

**Comment by moneroexamples** [comment]
@hyc 

Thanks. I will look into the `mdb_stat` stats. The explorer has only few threads. So the issue may come from the accumulation of the stale readers over time. Will look into it.
