### ISSUE TITLE
Weird timestamps

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-blockchain-explorer#46]
https://xmrchain.net/ has weird timestamps, older blocks have smaller time differences than new blocks. i don't know if this is the same time stamping weirdness that we've always seen or if its unique to the explorer.

**Comment by moneroexamples** [comment]
Thanks. Can you provide some example? Not sure what you mean.

**Comment by Gingeropolous** [comment]
<blockquote class="imgur-embed-pub" lang="en" data-id="a/FMFJE"><a href="//imgur.com/FMFJE"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by moneroexamples** [comment]
I see now:-) I will look into it. thx.

**Comment by moneroexamples** [comment]
I made new branch with the possible fix: https://github.com/moneroexamples/onion-monero-blockchain-explorer/tree/fix_tx_timestamps_index2

I need to just double check this, before merging to master.

I think the problem was that age was calcualted using global `server_timestamp` variable. Every request to the explorer will update this variable. Thus if the update happens in the middle of generating index.html, the age will be incorrect. 

the fix makes local copy of the `server_timestamp` at the beginning of index page generation, so that it does not change in the middle.

**Comment by moneroexamples** [comment]
I think its fixed now.

**Comment by jonathancross** [comment]
Seems this can be closed?

**Comment by moneroexamples** [comment]
@jonathancross 

Thanks. You are correct. I close now. @Gingeropolous can reopen later if some issues persist.
