### ISSUE TITLE
transaction not being displayed

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-blockchain-explorer#56]
A super ring size transaction shows up on moneroblocks but not xmrchain: https://xmrchain.net/search?value=1292610 , http://moneroblocks.info/search/1c51a4a70873fae13695fd9a0fd7127a3e9b5b9c771def7c3740b23a7ec4ccb5

And I get this from the output of xmrblocks (hard to tell if its exactly this because servers getting requests from others)

Apr 20 12:13:17 iof1006e clearnet_exp.sh[25793]: 2017-04-20 12:13:17.237            7f63bc651700        WARN         blockchain.db.lmdb        src/blockchain_db/lmdb/db_lmdb.cpp:71        Attempt to get block from height 1292619 failed -- block not in db
Apr 20 12:13:17 iof1006e clearnet_exp.sh[25793]: xmreg::timestamp_to_str: Unable to get Timezone database version from /home/monerosupport/Downloads/tzdata/
Apr 20 12:13:17 iof1006e clearnet_exp.sh[25793]: Seems cant convert to UTC timezone using date library. So just use local timezone.
Apr 20 12:13:17 iof1006e clearnet_exp.sh[25793]: Block of height 1292619 not found in the blockchain!Attempt to get block from height 1292619 failed -- block not in db
Apr 20 12:13:17 iof1006e clearnet_exp.sh[25793]: Cant get block: 1292619

Is my DB corrupt?

**Comment by Gingeropolous** [comment]
And this explorer (which uses your code with a pretty interface) shows it at a different block! 

https://monerohash.com/explorer/tx/1c51a4a70873fae13695fd9a0fd7127a3e9b5b9c771def7c3740b23a7ec4ccb5/1

**Comment by Gingeropolous** [comment]
OK, well it shows up. Im an idiot. 

https://xmrchain.net/search?value=1292454

But the search doesn't work for that tx ID. Im thinking its specific to my server instance of xmrblocks for some reason. Maybe its timing out for the response with all those data its trying to load?

**Comment by moneroexamples** [comment]
Maybe it was some bug in earlier code. Block numbering was buggy in monero before (shifted by one), block explorer was modify to work around it, and then monero fixed that, and its possible that the version of explorer you running still has this workaround, not needed now.

The best way to check what works or does not work in the explorer is by viewing its current development version http://139.162.32.245:8081/:

http://139.162.32.245:8081/search?value=1292610
http://139.162.32.245:8081/tx/1c51a4a70873fae13695fd9a0fd7127a3e9b5b9c771def7c3740b23a7ec4ccb5

The reason you  may not see this tx is because preparation of its html in the explorer is time consuming and browser is timing out. Preparation of timescale and details of mixins of mixins is time consuming by it self as they are not normally variable in tx data structures. This has already been simplified in the current development branch.
