### ISSUE TITLE
Latest code for dvwae436pd7nt4bc.onion ?

### ISSUE THREAD

**Issue by jonathancross** [moneroexamples/onion-monero-blockchain-explorer#66]
I am seeing mismatches between the code here and that being served from _dvwae436pd7nt4bc.onion_ -- should they match?

As a simple sanity check, I compared the HTML titles:
* [header.html#L9](/moneroexamples/onion-monero-blockchain-explorer/blob/master/src/templates/header.html#L9) :
`<title>Onion Monero Blockchain Explorer</title>` 
* dvwae436pd7nt4bc.onion  :
`<title>Monero Explorer</title>`

**Comment by suhz** [comment]
_dvwae436pd7nt4bc.onion_ (explorer.xmr.my) is currently using unmerged branch `add_network_info_front_page `

and the front-end template is from
https://github.com/suhz/onion-monero-blockchain-explorer/tree/new_template/src/templates

thus explain the difference.

**Comment by jonathancross** [comment]
Thanks @suhz. Will those change from your fork be merged upstream to this repo or should people submit PRs to your fork?

**Comment by suhz** [comment]
@jonathancross I'll do PR to this repo once `add_network_info_front_page` is merged, because my templates depends on that branch.

**Comment by moneroexamples** [comment]
@suhz @jonathancross

I can merge branch `add_network_info_front_page` now, unless you have some issues or feature request for the network info? Currently, working on making [mempool processing and monitoring in its own thread](https://github.com/moneroexamples/onion-monero-blockchain-explorer/issues/65), so I'm not adding anything new to network info. The emission numbers seem to be good now from what I can test.

One note though. The git procedure for building monero changed. Before it had `git checkout -b v0.10.3.1` which was incorrect. This was just creating branch called `v0.10.3.1`, rather than checking out release tag `v0.10.3.1`. The line was changed to: `git checkout -b last_release v0.10.3.1`. So you might need to redo monero compilation if the compilation fails.

**Comment by jonathancross** [comment]
> I can merge branch add_network_info_front_page now...

Sounds good to me  :-)

**Comment by suhz** [comment]
@moneroexamples I don't have anything to add :-)

**Comment by moneroexamples** [comment]
@suhz @jonathancross 

Merged :-)

**Comment by jonathancross** [comment]
Cheers  :-)
@moneroexamples Did you want to keep the front-end template stored in @suhz's repo or would it make sense to maintain that here as well?  Personally I expected to find the template code here,  but we could update the README to point out front-end template locations.

**Comment by moneroexamples** [comment]
@jonathancross 

I think link to @suh'z repo would be better. I like to keep onion explorer very basic so that its easier to  change its frontend or backend for anyone in their own versions if the want. 

Do you want to make PR to add the link it to readme?

**Comment by suhz** [comment]
@jonathancross At first I was thinking to PRs to @moneroexamples , but then I think it would be easier for me to maintain my front-end version of my explorer in its own repo. And, If anyone interested with that version, they can freely use that :)

**Comment by jonathancross** [comment]
> Do you want to make PR to add the link it to readme?

@moneroexamples  Cheers: #67
