### ISSUE TITLE
[Feature] Allow forward-navigation of outputs

### ISSUE THREAD

**Issue by pinkbrad** [moneroexamples/onion-monero-blockchain-explorer#80]
It would be very useful to be able to look at transactions and see when and where the tx output is used. Right now they can only trace backwards, seeing where an input came from. Going forwards would let people see how often they get used in transactions and give people a more tangible sense of Monero's privacy.

**Comment by moneroexamples** [comment]
Thanks, but unfortunately i dont think this will be added to the explorer in forcible future. The reason is that this would require exhaustive search over all txs to check when given output was used as a ring member. Alternatively, a dedicated database would need be constructed to keep track of these associations. Both solutions are not very good, one would be very time consuming, and second would add additional complexity in maintaining, setting up and hosting the explorer. 

However, a separate tool for that could be created, independent of the explorer. But currently I dont have a timefrime when it could be developed.

**Comment by pinkbrad** [comment]
Would you or someone you know be interested in a bounty to help work on this and the privacy-tx-statistics feature? 

We would be happy to donate to running hardware, too. This information is critical for users to really feel how Monero works within their privacy and anonymity concepts.

**Comment by moneroexamples** [comment]
I've been interested in searching when and where user's outputs (and tx stats now) are used in ring members for a while now, as this issue often comes up. But at the moment I cant take on new projects due to time limitations. In December I expect to have more time on my hands, so I can revisit this development. Unfortunately I cant think of anyone who could do it at present, so I keep the issue open.

**Comment by moneroexamples** [comment]
I modified other project, and added ring members basic stats, example outputs is here

https://github.com/moneroexamples/transactions-export#searching-txs-which-use-our-outputs-as-ring-members-and-their-frequency

Its a command line tool, nothing online or with fancy gui. But i think it does the job, of at least, showing how ring members frequencies can be obtained as basis of future developments
