### ISSUE TITLE
"link to this page" generates broken link with localhost:8888 as hostname

### ISSUE THREAD

**Issue by martypete1** [moneroexamples/onion-monero-blockchain-explorer#87]
When proving a transaction (https://xmrchain.net/prove) or decoding (https://xmrchain.net/myoutputs/) there is a link at the bottom:

"link to this page"

This generates the appropriate URL, with one exception: it uses localhost:8888 instead of the TLD https://xmrchain.net causing the link to be broken. Seem like it would be an easy fix. The link works if you put in the https://xmrchain.net instead of localhost:8888. Thanks.

**Comment by moneroexamples** [comment]
Thanks you right. This has been already fixed in newer versions of the explorer than that running at https://xmrchain.net. For example, https://moneroexplorer.com does not have this issue.  Thus have to wait till gets updated https://xmrchain.net. I'm not hosting https://xmrchain.net, thus don't know when it will be updated. Usually its updated when new version monero is released.
