### ISSUE TITLE
Bulletproof compatibility

### ISSUE THREAD

**Issue by Gingeropolous** [moneroexamples/onion-monero-blockchain-explorer#90]
I recently updated the daemon to master, and I can't see any bulleproof transactions on the explorer

https://testnet.xmrchain.com/

**Comment by stoffu** [comment]
Have you rebuilt the explorer with the latest Monero code as well? I think the current explorer just works fine with v7 blocks, as long as it's properly linked with the latest Monero code. Here's what I get on my local explorer:

![screen shot 2017-12-18 at 18 32 35](https://user-images.githubusercontent.com/26077532/34099155-0f9e0d1e-e422-11e7-875d-cf0d71be5c4e.jpg)

Here's what I get on testnet.xmrchain.com:

![screen shot 2017-12-18 at 18 31 30](https://user-images.githubusercontent.com/26077532/34099247-4f78de1e-e422-11e7-8c19-a157463ec10b.jpg)

Notice that the block at height 1057244 is missing, probably due to the explorer not being able to parse BP txes.

**Comment by moneroexamples** [comment]
As @stoffu said need latest monero, and also the explorer from its latest development branch:

https://github.com/moneroexamples/onion-monero-blockchain-explorer/tree/devel

**Comment by Gingeropolous** [comment]
sorry, my bad. Will pull and compile
